#! /bin/bash

echo Starting Qemu

kernel="${1}"
ramdisk="${2}"
usb_bus="${3}"
usb_port="${4}"
share_folder="${5}"
debug="${6}"

if [ -n "${debug}" ]; then
    debug="-s -S"
fi

qemu-system-x86_64 \
    -kernel "${kernel}" \
    -display none \
    -serial mon:stdio \
    -cpu host \
    -append "console=ttyS0 rw earlyprintk nokaslr nolapic_timer=1 noapictimer=1 disable_cpu_apicid=1" \
    -enable-kvm \
    -initrd "${ramdisk}"  \
    -m 1024 \
    -device usb-ehci,id=ehci \
    -device usb-host,bus=ehci.0,hostbus="${usb_bus}",hostport="${usb_port}" \
    -virtfs local,path=${share_folder},mount_tag=shared,security_model=passthrough,id=shared \
    -netdev user,id=eth0 \
    -device e1000,netdev=eth0 \
    ${debug}

